### ISSUE TITLE
Add to Emacs core?

### ISSUE THREAD

**Issue by astoff** [federicotdn/flymake-shellcheck#11]
Have you considered adding this Flymake backend to Emacs itself? The main advantage is that everything would work out-of-the-box without requiring the user to discover and install yet another package.

This would require signing some copyright-assignment papers with the FSF, but otherwise the process is very simple.  The first step would be to write the necessary changes to sh-script.el, then email a patch to bug-gnu-emacs@gnu.org.

If you are unable or not interested in doing this, I'm considering submitting a new implementation to Emacs. Please let me know what you think.

**Comment by federicotdn** [comment]
Hi,
I have contributed to Emacs core in the past, but I've changed company recently so I would need to update my copyright assignment and then open a bug report to propose the addition of this module. I'm not sure what would be needed to be done with regards to the other 4 contributors of this project.

In any case, I don't think I will get to doing this in the near future, so feel free to propose your own solution into Emacs core. You can reuse code from this project in case that helps 😃 . Then when Emacs 29 is released I can add a disclaimer to this project's README.

**Comment by astoff** [comment]
Emacs 29 now has a shellcheck Flymake backend :-).
