### ISSUE TITLE
How to enable on-the-fly checking?

### ISSUE THREAD

**Issue by grolongo** [federicotdn/flymake-shellcheck#2]
Hello,

I successfuly installed your package using use-package on Windows and macOS (both with Emacs 27.1) and the checking works as expected.

What I didn't succeed to tweak though was the on-the-fly checking instead of on-save only.

Flymake provides on-the-fly checking for Elisp by default and that works. I was wondering why this didn't work for shellcheck?

Thanks for your help and thank you again for making this package.

**Comment by federicotdn** [comment]
Hey! Please check the new `flymake-shellcheck-use-file` variable I've introduced for this, you should set it to `nil`. You will probably need to wait until MELPA picks up the changes from `master` (and maybe restart Emacs).

**Comment by grolongo** [comment]
Hey @federicotdn, just tried your last commit and the new setting works flawlessly. Thank you!
