### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by MorganJamesSmith** [federicotdn/flymake-shellcheck#4]
When compiling this package from a clean Emacs state I get the following error:
```
Wrong type argument: listp, end
```

This is fixed by putting
```
(require 'flymake)
```
at the top of the file

Here is a link to a GNU Guix build server that attempted to compile this package and failed (to prove I'm not the only one having this issue): http://ci.guix.gnu.org/build/222782/details

**Comment by federicotdn** [comment]
Thanks for bringing this up. Would you mind opening a PR for it?
