### ISSUE TITLE
Don't look for the executable at package load time

### ISSUE THREAD

**Issue by astoff** [federicotdn/flymake-shellcheck#6]
It's better not to call `(executable-find "shellcheck")` at load time. This is incompatible with "project environment management" packages like direnv, envrc, buffer-env and various virtualenv integration packages which change the `exec-path` during runtime. I suggest renaming `flymake-shellcheck-path` to `flymake-shellcheck-program` and calling `executable-find` only inside `flymake-shellcheck--backend`.

Also, this check is already made by `executable-find` anyway: https://github.com/federicotdn/flymake-shellcheck/blob/ac534e9ef15c82ac86ae65fe5004d29dbc8c92c7/flymake-shellcheck.el#L65

**Comment by federicotdn** [comment]
Hi @astoff, thanks for reporting this. I have not been using Shellcheck a lot lately - would you mind opening a PR for this? Otherwise, let me know and I'll look into it.
